##########################################################################################
# Copyright (c) 2022 Logan Barnes - All Rights Reserved
##########################################################################################

function(ltb_add_executable target)
    add_executable(${target} ${ARGN})
    target_link_libraries(${target} PRIVATE doctest::doctest)
    target_compile_definitions(${target} PRIVATE DOCTEST_CONFIG_DISABLE)
    if (${LTB_ENABLE_TESTING})
        add_executable(test-${target} ${ARGN})
        target_link_libraries(test-${target} PRIVATE doctest::doctest)
    endif ()
endfunction()

function(ltb_add_library target)
    add_library(${target} ${ARGN})
    target_link_libraries(${target} PRIVATE doctest::doctest)
    target_compile_definitions(${target} PRIVATE DOCTEST_CONFIG_DISABLE)
    if (${LTB_ENABLE_TESTING})
        add_executable(test-${target} ${ARGN} ${CMAKE_CURRENT_LIST_DIR}/src/ltb/test/main.cpp)
        target_link_libraries(test-${target} PRIVATE doctest::doctest)
    endif ()
endfunction()

function(ltb_target_compile_definitions target)
    target_compile_definitions(${target} ${ARGN})
    if (TARGET test-${target})
        target_compile_definitions(test-${target} ${ARGN})
    endif ()
endfunction()

function(ltb_target_compile_features target)
    target_compile_features(${target} ${ARGN})
    if (TARGET test-${target})
        target_compile_features(test-${target} ${ARGN})
    endif ()
endfunction()

function(ltb_target_compile_options target)
    target_compile_options(${target} ${ARGN})
    if (TARGET test-${target})
        target_compile_options(test-${target} ${ARGN})
    endif ()
endfunction()

function(ltb_target_include_directories target)
    target_include_directories(${target} ${ARGN})
    if (TARGET test-${target})
        target_include_directories(test-${target} ${ARGN})
    endif ()
endfunction()

function(ltb_target_link_libraries target)
    target_link_libraries(${target} ${ARGN})
    if (TARGET test-${target})
        target_link_libraries(test-${target} ${ARGN})
    endif ()
endfunction()

function(ltb_target_sources target)
    target_sources(${target} ${ARGN})
    if (TARGET test-${target})
        target_sources(test-${target} ${ARGN})
    endif ()
endfunction()
